from tkinter import Tk,Label,Frame

w=Tk()

w.title("VIBGYOR")
w.geometry("700x100")

F1=Frame(w,width=100,height=100,bg="violet")
F2=Frame(w,width=100,height=100,bg="indigo")
F3=Frame(w,width=100,height=100,bg="blue")
F4=Frame(w,width=100,height=100,bg="green")
F5=Frame(w,width=100,height=100,bg="yellow")
F6=Frame(w,width=100,height=100,bg="orange")
F7=Frame(w,width=100,height=100,bg="red")
F1.grid_propagate(False)
F2.grid_propagate(False)
F3.grid_propagate(False)
F4.grid_propagate(False)
F5.grid_propagate(False)
F6.grid_propagate(False)
F7.grid_propagate(False)
F1.grid(row=0,column=0)
F2.grid(row=0,column=1)
F3.grid(row=0,column=2)
F4.grid(row=0,column=3)
F5.grid(row=0,column=4)
F6.grid(row=0,column=5)
F7.grid(row=0,column=6)

L1=Label(F1,text="V",bg="violet",fg="black",font=("italic 20 bold"))
L2=Label(F2,text="I",bg="indigo",fg="black",font=("italic 20 bold"))
L3=Label(F3,text="B",bg="blue",fg="black",font=("italic 20 bold"))
L4=Label(F4,text="G",bg="green",fg="black",font=("italic 20 bold"))
L5=Label(F5,text="Y",bg="yellow",fg="black",font=("italic 20 bold"))
L6=Label(F6,text="O",bg="orange",fg="black",font=("italic 20 bold"))
L7=Label(F7,text="R",bg="red",fg="black",font=("italic 20 bold"))
L2.grid(row=0,column=0)
L3.grid(row=0,column=0)
L4.grid(row=0,column=0)
L5.grid(row=0,column=0)
L6.grid(row=0,column=0)
L7.grid(row=0,column=0)
L1.grid(row=0,column=0)

w.mainloop()